baseURL = 'https://mrunix.me'
languageCode = 'en-us'
title = 'Mr.UNIX'

[menu]

[[menu.main]]
    name = 'Posts'
    url = '/posts/'
    pre = 'pen-tool'

[[menu.main]]
    name = 'Resume'
    url = '/resume.pdf'
    params = { download = true }

[markup]
  [markup.highlight]
    style = 'github-dark'
