baseURL = 'https://mrunix.me'
languageCode = 'en-US'
title = 'Mr.UNIX'
enableRobotsTXT = true

[menu]

[[menu.main]]
    name = 'Posts'
    url = '/posts/'
    pre = 'pen-tool'
    weight = 10

[[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 20

[[menu.main]]
    name = 'Devices'
    url = '/devices/'
    weight = 30

[[menu.main]]
    name = 'Resume'
    url = '/resume.pdf'
    weight = 40
    params = { download = true }

[markup]
  [markup.highlight]
    style = 'github-dark'
